In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [9]:
import numpy as np

a = np.array(4)

print(a.ndim)
print("ndim tells the dimensions")

0
ndim tells the dimensions


In [11]:
arr = np.array([1,43,65,7,3,4])
print(arr)
print(arr.ndim)

[ 1 43 65  7  3  4]
1


In [12]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2
